# Baseline Model Prediction

## Imports and Setups

In [64]:
%load_ext autoreload
%autoreload 2

# This sets up the appropriate logging and path configs
from notebook_setup import * 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [65]:
# External Packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

from sklearn.linear_model import LogisticRegression
from sklearn.utils import column_or_1d
from sklearn.preprocessing import OneHotEncoder

## Import Diabetes Dataset

In [66]:
df_train = pd.read_csv("data/interim/train.csv")
df_test = pd.read_csv("data/interim/test.csv")

In [67]:
X_train = df_train.loc[:, df_train.columns != 'diabetes']
y_train = df_train.loc[:, df_train.columns == 'diabetes']

X_test = df_test.loc[:, df_test.columns != 'diabetes']
y_test = df_test.loc[:, df_test.columns == 'diabetes']

## Train

In [68]:
import numpy as np
from sklearn.dummy import DummyClassifier
dummy_clf = DummyClassifier(strategy="most_frequent")
dummy_clf.fit(X_train, y_train)
dummy_clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [69]:
dummy_clf.score(X_test, y_test)

0.915

log reg

In [70]:
logreg = LogisticRegression(random_state=42)

In [71]:
enc = OneHotEncoder(handle_unknown='ignore')
X_train_processed = enc.fit_transform(X_train)
X_test_processed = enc.transform(X_test)
enc.categories_

[array([    0,     1,     2, ..., 99997, 99998, 99999], dtype=int64),
 array(['Female', 'Male', 'Other'], dtype=object),
 array([ 0.08,  0.16,  0.24,  0.32,  0.4 ,  0.48,  0.56,  0.64,  0.72,
         0.8 ,  0.88,  1.  ,  1.08,  1.16,  1.24,  1.32,  1.4 ,  1.48,
         1.56,  1.64,  1.72,  1.8 ,  1.88,  2.  ,  3.  ,  4.  ,  5.  ,
         6.  ,  7.  ,  8.  ,  9.  , 10.  , 11.  , 12.  , 13.  , 14.  ,
        15.  , 16.  , 17.  , 18.  , 19.  , 20.  , 21.  , 22.  , 23.  ,
        24.  , 25.  , 26.  , 27.  , 28.  , 29.  , 30.  , 31.  , 32.  ,
        33.  , 34.  , 35.  , 36.  , 37.  , 38.  , 39.  , 40.  , 41.  ,
        42.  , 43.  , 44.  , 45.  , 46.  , 47.  , 48.  , 49.  , 50.  ,
        51.  , 52.  , 53.  , 54.  , 55.  , 56.  , 57.  , 58.  , 59.  ,
        60.  , 61.  , 62.  , 63.  , 64.  , 65.  , 66.  , 67.  , 68.  ,
        69.  , 70.  , 71.  , 72.  , 73.  , 74.  , 75.  , 76.  , 77.  ,
        78.  , 79.  , 80.  ]),
 array([0, 1], dtype=int64),
 array([0, 1], dtype=int64),
 array(['

In [72]:
logreg = logreg.fit(X_train_processed, column_or_1d(y_train))

c:\Users\zifen\Documents\Projects\diabetes-prediction\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [73]:
y_pred = logreg.predict(X_test_processed)

In [74]:
from sklearn.metrics import confusion_matrix


confusion_matrix(y_test, y_pred)

array([[18283,    17],
       [  540,  1160]], dtype=int64)

In [75]:
from sklearn.metrics import classification_report


print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98     18300
           1       0.99      0.68      0.81      1700

    accuracy                           0.97     20000
   macro avg       0.98      0.84      0.90     20000
weighted avg       0.97      0.97      0.97     20000

